### ISSUE TITLE
Add support for M1 Macs (.NET 6)

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Meadow.CLI#119]
No changes needed to CLI.Core

Looks like we can multitarget .NET 5 & 6

```<TargetFrameworks>net5.0;net6.0</TargetFrameworks>```

**Comment by adrianstevens** [comment]
I've tested this fix - only reason it's not committed is the CI doesn't currently support .NET 6

**Comment by CartBlanche** [comment]
@adrianstevens Do you have a branch with this fix already? If so I can clone it, then try to tweak the CI there, so that it builds. If not, I'll create a new branch.

**Comment by NevynUK** [comment]
Fixed in CLI 0.19.3 released on 30th May 2022.
