### ISSUE TITLE
meadow flash esp with version/file

### ISSUE THREAD

**Issue by ctacke** [WildernessLabs/Meadow.CLI#199]
Trying to flash just the ESP with a version number fails with "meadow did not accept command".

Also , the API supports giving it a file but the CLI does now (and since it's really 3 files, how would that work?)

**Comment by adrianstevens** [comment]
Ha ... the API _shouldn't_ support giving it a file ... I'll take a look

**Comment by adrianstevens** [comment]
Fixed in CLI v2 - closing issue
