### ISSUE TITLE
Unwanted meadow flash verification

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#210]
Meadow F7 with OS and RT 0.6.7.56 deployed

Deploying the ESP32 code using CLI with the command

`meadow flash os -v 0.6.7.55 -d -k`

This generates the following message:

```
Your OS or runtime version is older than 0.6.1.0. A flash erase is highly recommended.
Proceed? (Y/N) Press Y to erase flash, N to continue install without erasing
```

The CLI has been told to ignore DFU and the RT deployment.

**Comment by adrianstevens** [comment]
great - I'll get that fixed

**Comment by adrianstevens** [comment]
This has been removed in CLI v2

**Comment by adrianstevens** [comment]
Shipped in v2 - closing issue
