### ISSUE TITLE
Request: Extend list ports to use a port

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#223]
Add an option to `meadow list ports` to use a port if there is only one meadow device connected.

Adding an additional option to use the port would ease the case where the user issues the commands

* `meadow list ports`
* `meadow use port xxxxxxx`

**Comment by adrianstevens** [comment]
Maybe we configure 'meadow use port' to work without an argument if there's only one port?

I feel like selecting a port when calling list is overfunctioning - pun intended ;)

**Comment by CartBlanche** [comment]
@NevynUK there was some talk about streamlining this experience. 
eg. If there is only 1 device present, the user should not have to select it, it should detect there is only 1 and do some magic under the hood to auto-select and use it. 
If there is more than 1 device attached, then it can pull up a dynamically numbered list with each device and the user can select the device via the command line prompt and it automagically uses that device and continues.
Those were the original thoughts anyway. Just less paper cuts in the CLI experience.

**Comment by adrianstevens** [comment]
@CartBlanche we should sync and talk strategy

**Comment by adrianstevens** [comment]
`meadow select port` will automatically select the port if there's only one available in CLI v2

closing issue
