### ISSUE TITLE
Stdout from Meadow is output as ASCII instead of UTF-8

### ISSUE THREAD

**Issue by bcr** [WildernessLabs/Meadow.CLI#278]
My fancy Meadow app has UTF-8 output. This is turned into ASCII when monitoring with `meadow listen`. I know where to make the change, but I think it may affect other stuff. Works on my machine when using `meadow listen` but will probably explode if presented with non-UTF8 bytes with the high bit set.

https://github.com/WildernessLabs/Meadow.CLI/blob/develop/Meadow.CLI.Core/Internals/MeadowCommunication/ReceiveClasses/ReceiveSimpleText.cs#L31

**Comment by CartBlanche** [comment]
@bcr what languages are you using?

**Comment by bcr** [comment]
English. I was using the Degree Fahrenheit character \u2109.

**Comment by CartBlanche** [comment]
@bcr I've create a PR here - https://github.com/WildernessLabs/Meadow.CLI/pull/279 
If you are feeling brave, this will create a Meadow.CLI  artefact here https://github.com/WildernessLabs/Meadow.CLI/actions/runs/4679452989 when finished, which you can install and test as follows, after you've downloaded it an extracted the zip file, grab the nuget from `Meadow.CLI/bin/Release` folder named WildernessLabs.Meadow.CLI.0.97.0-alpha.nupkg...

* dotnet tool uninstall --global WildernessLabs.Meadow.CLI
* dotnet tool install --global --add-source [your-download-dir] WildernessLabs.Meadow.CLI --version 0.97.0-alpha

if you find this alpha version unstable and want to go back to the latest stable version:

* dotnet tool uninstall --global WildernessLabs.Meadow.CLI
* dotnet tool install --global WildernessLabs.Meadow.CLI

**Comment by bcr** [comment]
Yeah, that's basically what I did initially and it did what I expected. I submitted #280 which might be a more timid approach.

I just run it with `dotnet run --framework net6.0 -- listen` and it works -- do you prefer that I install it as a tool to test it?

**Comment by CartBlanche** [comment]
@bcr if you have the cycles to install it as a tool, that would be great. Just to cover all bases.

**Comment by CartBlanche** [comment]
Fixed in #279.
