### ISSUE TITLE
Decouple linker from deploy

### ISSUE THREAD

**Issue by lamebrain** [WildernessLabs/Meadow.CLI#287]
Currently, linking only occurs when deploying to a device. We want to be able to run the linker before creating a package (MPAK).

**Comment by CartBlanche** [comment]
Linking should really be part of the build process. 
@lamebrain so do we need to hook into each IDEs "package" feature too?
What about "publish" from IDEs, will we support an app hub/shop in future?

**Comment by lamebrain** [comment]
@CartBlanche  Ideally, it's part of the build process, that should be feasible within the IDEs. I normally build through the command line... can we hook into `dotnet build`? If not, we can make a separate CLI command to link out unneeded items.

We'll definitely want to pack and publish from the IDEs in the future. A shop is an interesting idea, we don't have plans for anything like that yet, but definitely Meadow.Cloud for now.

**Comment by jorgedevs** [comment]
@CartBlanche any updates on this? this would really improve the experience of using OTA updates without the need to first deploy the app with a machine every time.

**Comment by CartBlanche** [comment]
@jorgedevs Once I sort out the VSCode PR, I hope to have a look at this again. Jon already started on it, but due to other priorities, hasn't had a chance to finish that PR. So I'll take a look and see if I can make some progress on it.

**Comment by adrianstevens** [comment]
The code has been isolated and cleaned up in CLI v2

**Comment by adrianstevens** [comment]
Fixed in v2.0.x - closing issue
