### ISSUE TITLE
dfu-util upgrade warning

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#350]
The command `meadow flash os -e -v 1.1.0.0` results in the message:

```
Flashing OS with /Users/<username>/.local/share/WildernessLabs/Firmware/1.1.0.0/Meadow.OS.bin
dfu-util update required. To install, run: brew upgrade dfu-util
```

`meadow --version` - 1.3.0

`dfu-util` - version 0.11

Checking with brew:

* `brew update`
* `brew upgrade dfu-util`

Results in `Warning: dfu-util 0.11 already installed`

**Comment by NevynUK** [comment]
Corrected version numbers in original post.

**Comment by CartBlanche** [comment]
Some binaries should be available here shortly - https://github.com/WildernessLabs/Meadow.CLI/actions/runs/6226068544
