### ISSUE TITLE
Reformat meadow listen output...

### ISSUE THREAD

**Issue by CartBlanche** [WildernessLabs/Meadow.CLI#387]
From: @bryancostanich 
When you do `meadow listen` there are extra line breaks in there. 
- [ ] can we remove them?
- [ ] instead of stdout> could we do something like: 2023.10.23-15:35.05>

**Comment by DarkNoir** [comment]
Yes please

**Comment by adrianstevens** [comment]
You can configure Meadow.Logger to include timestamps from the app on device.

And in CLI v2.x it's possible to disable the output prefix.

Thanks all - closing issue. Feel free to re-open if we want to discuss further.
