### ISSUE TITLE
CLI V2 `mono update rt` or equivalent is missing

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#393]
Part of the workflow for OS development is to update the board with the latest compiled OS and runtime system.

The run time is currently updated (with V1) using the command `meadow mono update rt -f Meadow.OS.Runtime.bin` in the directory containing the runtime file.

The ESP32 could also updated with a specific command such as `meadow esp32 file write -f ./MeadowComms.bin --McuDestAddress 0x10000`

The first command (or a new equivalent) is required for the OS development, the second is a nice to have.

**Comment by adrianstevens** [comment]
This has been added to CLI v2

**Comment by adrianstevens** [comment]
shipped - closing issue
