### ISSUE TITLE
Timeout communicating with Meadow

### ISSUE THREAD

**Issue by Perun85** [WildernessLabs/Meadow.CLI#43]
I am experiencing issues while trying to update ESP32 coprocessor using CLI.

Version: Meadow.CLI 0.12.3

According to console, step where Mono runtime is disabled went well.

![image](https://user-images.githubusercontent.com/6298686/103028997-262fba00-4559-11eb-8cdb-9dbc30f7a0a2.png)

Same goes for runtime update.

![image](https://user-images.githubusercontent.com/6298686/103029271-bcfc7680-4559-11eb-83c7-a38ee5e3f80e.png)

But, when I try to update coprocessor I get following error.

![image](https://user-images.githubusercontent.com/6298686/103029560-5592f680-455a-11eb-9996-2ecd8feec772.png)

Perhaps I am doing something wrong?

**Comment by thegreatco** [comment]
This should be fixed in the CLI rewrite, please pull the latest and let me know if you still encounter this issue

**Comment by Perun85** [comment]
With the latest CLI version it is working without issues.

**Comment by thegreatco** [comment]
@Perun85 thanks for the update!
