### ISSUE TITLE
Return a non-zero exit code when an error occurs

### ISSUE THREAD

**Issue by stevenkuhn** [WildernessLabs/Meadow.CLI#453]
In the current implementation of the CLI, when an error occurs the error is logged and execution stops with the standard exit code of zero. However this causes issues when users and other command-line tools expect a non-zero exit code when an error occurs. An example of this is when the user is chaining multiple commands with `&&` in the command-line. The expectation is that an error with Meadow.CLI should not allow the command chain to continue. 

In order to support returning exit codes with `CliFx`, the commands must throw `CommandException`: https://github.com/Tyrrrz/CliFx?tab=readme-ov-file#reporting-errors

**Comment by adrianstevens** [comment]
Shipped in v2.0.x - closing issue
