### ISSUE TITLE
dfu-util Update Required Warning Shows Older CLI Message

### ISSUE THREAD

**Issue by mehalick** [WildernessLabs/Meadow.CLI#75]
When running the command `meadow flash os` with an outdated version of dfu-util the CLI shows an error/warning message with advice on how to update dfu-util. The message appears to recommend a command from a previous version of the CLI which may confuse new users:

```
❯ meadow flash os
Entering DFU Mode
Device in DFU Mode, flashing OS
Flashing OS with C:\Users\Andy\AppData\Local\WildernessLabs\Firmware\Meadow.OS.bin
dfu-util update required. To install, run in administrator mode: meadow --InstallDfuUtil
```

The CLI command `meadow --InstallDfuUtil` in v0.14.0 appears to be incorrect, I'm assuming it should be  `meadow install dfu-util`.

If I'm correct I can submit a simple PR to update the message, I'd love to get involved in this project.

**Comment by thegreatco** [comment]
Fixed in 0.14.1.
