### ISSUE TITLE
meadow fs format is unsupported

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#80]
HCOM is reporting that this option is not supported.

Message from HCOM: `(Error) comms/hcom_host_route.c@404-Received unsupported request type:0x0103`

The above message can be seen in trace output.

**Comment by adrianstevens** [comment]
Fixed here: https://github.com/WildernessLabs/Meadow.CLI/commit/20bc19b0d6842c09d3eba26cf179159b02a211b7
 
closing issue
