### ISSUE TITLE
Error flashing F7 OS from a non-english OS

### ISSUE THREAD

**Issue by loicmorvan** [WildernessLabs/Meadow.CLI#82]
Because of the dirty `string.Contains` check in https://github.com/WildernessLabs/Meadow.CLI/blob/5f2ac4dce3419d7dc7ef8be3e7535661db99d0d4/Meadow.CLI.Core/Internals/Dfu/DfuUtils.cs#L226 when running the command on a non-english OS, an exception is thrown rather than returning an empty string.

This prevents flashing the board OS when running on a non-english computer OS.

**Comment by NevynUK** [comment]
Closed following beta 6.1 release.
