### ISSUE TITLE
Mono Enable does not always reset the board

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#86]
I'm not sure if this is how it is designed to work but `meadow mono enable` does not reset the board if mono is already enabled.

If this is as designed can we please have an option for `mono enable` to force a reset, say `-r`.

Background, I am deploying applications manually through the command line and keep having to remember to disable mono before re-enabling it in order for the newly deployed application to run.

**Comment by thegreatco** [comment]
Added a `--force`/`-f` parameter to both `mono enable` and `mono disable` commands
