### ISSUE TITLE
Add output indicating OS download has started

### ISSUE THREAD

**Issue by adrianstevens** [WildernessLabs/Meadow.CLI#88]
I'm testing on a slow PC and slow connection - it took 5-10s to download but it wasn't obvious anything was happening ... a simple "Meadow OS download started .... " would be great

**Comment by thegreatco** [comment]
Added via https://github.com/WildernessLabs/Meadow.CLI/commit/e6ed8e420b9ff8312a482ecbc86bc6d444eae57a
