### ISSUE TITLE
For Investigation: Flash OS issue observed during b5.3 testing

### ISSUE THREAD

**Issue by NevynUK** [WildernessLabs/Meadow.CLI#89]
During b5.3 testing there appeared to be some inconsistency with the file loaded on to the board.

`meadow flash os -o Meadow.OS.bin -r Meadow.OS.Runtime.bin`

seemed to write the RT from the directory the command was being executed from but the OS from the download cache.

The final board had 0.5.2.0 of the OS deployed with 0.5.3.0 of the RT.  This is consistent with the file in the cache being 0.5.2 and the files in the local directory being 0.5.3.

**Comment by NevynUK** [comment]
This is still a problem with CLI 0.15.1 (beta 0.6.0.1)

**Comment by NevynUK** [comment]
I also think this impacts `meadow flash os` as it exhibits the same behaviour.

**Comment by adrianstevens** [comment]
@CartBlanche for visibility - let's see if we can improve for B6.3

**Comment by adrianstevens** [comment]
@NevynUK I haven't been able to repo on Windows or Mac - lets talk and see if can get a consistent
 repro

**Comment by NevynUK** [comment]
Closed following beta 6.4 release.
