### ISSUE TITLE
CLI is ignoring the SerialPort command line parameter

### ISSUE THREAD

**Issue by HakanL** [WildernessLabs/Meadow.CLI#96]
When running the CLI with -s COMx and it calls `FindMeadowBySerialNumber` then this parameter is ignored. I'm not 100% sure what the correct fix is, but I noticed this when the CLI tried to open a port named "R" on my machine during the "Fallback to brute force searching" portion in this method. It should only try the specified port IMO.

**Comment by adrianstevens** [comment]
This has been fixed - closing issue
